#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: source export_test_env username password"
fi

export COBRADB_POSTGRES_HOST=localhost
export COBRADB_POSTGRES_PORT=5432
export COBRADB_POSTGRES_USER=$1
export COBRADB_POSTGRES_PASSWORD=$2
export COBRADB_POSTGRES_DATABASE=cobradb
export COBRADB_POSTGRES_TEST_DATABASE=cobradb_test
